### ISSUE TITLE
Permission set out of date

### ISSUE THREAD

**Issue by BFresco** [Tools4everBV/HelloID-Conn-Prov-Target-Azure-Permissions#1]
The permission set has been updated by Microsoft and requires the addition of the following permission for **Application** use:

- GroupMember.ReadWrite.All

See [Add Member - Permissions](https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#permissions)

**Comment by rschouten97** [comment]
Hi @BFresco the permission set is not exactly outdated.
The permissions **User.ReadWrite.All** and  **Group.ReadWrite.All** (or even Directory.ReadWrite.All) still grant permision to update the members of the group.
It's just that another permission has been added which grants the option to update the members of the group without the above mentioned permissions.

I agree that we should update our readme on this.
But just to clarify; the current permissions in our readme still suffice.
