### ISSUE TITLE
Script doesn't support the possibility to grant role-assignable groups

### ISSUE THREAD

**Issue by BFresco** [Tools4everBV/HelloID-Conn-Prov-Target-Azure-Permissions#2]
In addition to the updated permission set, it is also not possible to assign user accounts to role-assignable groups in Azure, this requires the addition of the following permission:

- RoleManagement.ReadWrite.Directory

**Comment by rschouten97** [comment]
Hi @BFresco  this permission set is not required when you already have Directory.ReadWrite.All.
However, I do agree that we could and should include a note about this in the readme.

But just to clarify; the permission Directory.ReadWrite.All will suffice.
