### ISSUE TITLE
dynamic permissions teams [2.0.0]

### ISSUE THREAD

**Issue by mouki9** [Tools4everBV/HelloID-Conn-Prov-Target-Azure-Permissions#8]
In the new Powershell v2 repo, the part for dynamic permissions for team groups is incorrect. 
The filter used in line 250:

`$filter` = "resourceProvisioningOptions/Any(x:x eq 'Team') & displayName+eq+'$($teamName)'"

should be the other way around

`$filter` = "displayName+eq+'$($teamName)' & resourceProvisioningOptions/Any(x:x eq 'Team')"

The first filter return all the teams, the second one only the one we need.

**Comment by rschouten97** [comment]
@mouki9 nice catch, has been corrected
