### ISSUE TITLE
Readme [2.0.0]

### ISSUE THREAD

**Issue by mouki9** [Tools4everBV/HelloID-Conn-Prov-Target-Azure-Permissions#9]
please also update the readme to reflect the permissions needed to for example set and update the authenticationMethods. The default only takes into account the permissions to grant and revoke the permissions and to read the users.

**Comment by rschouten97** [comment]
@mouki9 , there was already a reference to the permission required, only there was a copy-paste error, where it still referenced the groupmember permissions.
This has been corrected to:
Read and write all users' authentication methods by using *UserAuthenticationMethod.ReadWrite.All*
